#!/usr/bin/env bash
set -e

# use deepseek as the engine instead of claude
# https://api-docs.deepseek.com/guides/anthropic_api

DEEPSEEK_API_KEY="sk-00000"
MODEL="deepseek-chat"   # or deepseek-reasoner
MODEL="deepseek-reasoner"

exec env \
  ANTHROPIC_BASE_URL="https://api.deepseek.com/anthropic" \
  ANTHROPIC_AUTH_TOKEN="$DEEPSEEK_API_KEY" \
  ANTHROPIC_MODEL="$MODEL" \
  claude "$@"
